#+OPTIONS: num:nil toc:nil

#+TITLE: SI618 Project II Proposal

* Problem Statement
Overwatch is a multiplayer team-based first-person shooter video game. At the moment Overwatch has over 35 million
players worldwide across different skill levels. Overwatch offers a competitive game mode, in which players can
engage in competitive matches and build up their Skill Ratings (SR) by winning those matches. This project aims at
uncovering what distinguishes the high level players from others and whether or not SR reflects players' skill
levels accurately. 

* Data
Players' statistics can be found on various website including the [[https://playoverwatch.com][official Overwatch website]] and [[https://overwatchtracker.com][overwatchtracker.com]].
Datasets used in this project are scraped from these two websites using R package =rvest=. We first scrape players'
battle tags (a form of player id) and general skill ranking information from overwatchtracker website. Then we use
the battle tags to access each individual player's career statistics page and scrape all relevant tables. The final
output contains information on 16500 players, each having around 200 or so small tables.

* Proposed Analyse
 - *Compare game stats between players in different levels.* For example, /melee final blows/ is believed to happen much more often at higher levels. A scatter plot of /melee final blows/ percentage versus SR can reveal more on this assumption.
 - *Compare the performance (win rate, eliminations, elim/death rate) of different heroes across all levels.* One idea is to rank the heroes by their (weighted) average win rate. 
 - *Evaluate how well support mains play dps heroes.* A player's main is decided by what type of heroes he/she plays the most. We can compare a support main's dps performance to a dps's performance having the same SR.
 - *Perform PCA on overall stats.* Then take the first two principal components and visualize on a scatter plot, points grouped by main hero type.
 - *Investigate heroes usage.* Rank heroes by their play time. This can be done for all players, high level players and low level players. Can also compare the ratio of the play time of each hero type. 
 - *Investigate the existence of "meta".* Meta is a term used among players to represent a certain team composition that has a higher chance to win. We will compare the win rate of meta heroes and that of other heroes to see if meta actually works.
 - *Build a model to predict a player's SR give his/her game stats.* Potential model choices include Random Forests, LASSO, Boosting, etc. This may be difficult as how SR is computed has always been a mystery and is often criticized for not representing skill level well enough. 
 - *Build a classification model to identify the player with the higher SR given two players' stats.* We can compute the log ratio of the two players for each stat and use these as predictors.

